### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [lee-soft/ViStart#15]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by lee-soft** [comment]
That's been added in this commit

https://github.com/lee-soft/ViStart/commit/71b7b0941d4942b98a356e4317e4f674ecb7dced
