### ISSUE TITLE
Compiled version of ViStart crashes on launch

### ISSUE THREAD

**Issue by basiccube** [lee-soft/ViStart#16]
ViStart crashes on launch with the error:
`PaintItems:: Subscript out of range (frmFreq)`
I can't even debug this as Visual Basic crashes alongside ViStart.
I've provided both the screenshot of the immediate window in Visual Basic and the errors.log file if that can help solve the issue.

![Screenshot 2023-02-15 144747](https://user-images.githubusercontent.com/67266535/219032489-071f0a22-3e33-4a6a-b4ad-0fb85c2aa80e.png)
[errors.log](https://github.com/lee-soft/ViStart/files/10743127/errors.log)

**Comment by lee-soft** [comment]
Could you find the HookWindow procedure in the "HookHelper" and immediately write "Exit Function" as the first line below the procedure header, then re run the project in the IDE please.

**Comment by basiccube** [comment]
That fixed the crash. Now the start menu being broken is the next issue.
![Screenshot 2023-02-15 152833](https://user-images.githubusercontent.com/67266535/219041207-5f736ef3-58e4-47e4-a38b-aa0df31433dd.png)

**Comment by lee-soft** [comment]
Remove the new 'Exit Function' you added,
find the frmFreq, Form_Load procedure and comment out the first line and re run again for me.

**Comment by lee-soft** [comment]
Can you discard all changes and pull the latest main branch and try running again?

**Comment by basiccube** [comment]
Thanks, that fixed it and it works now.
