### ISSUE TITLE
Sometimes a skin will not apply if selected too fast.

### ISSUE THREAD

**Issue by brunobits** [lee-soft/ViStart#27]
# Description
Title.

# How to replicate?
Select a skin while the previous one is still applying - the last selected one won't apply but it shows as selected in the dropdown menu.

# Expected behaviour
The last selected skin should apply.

# Demonstration
The next image shows the Windows XP Luna start menu theme applied, but the Windows Vista 5270 theme is the one selected.
![image](https://user-images.githubusercontent.com/48385307/221159803-f88d7bd9-69bb-47d7-927e-ddb891487ad0.png)

**Comment by lee-soft** [comment]
This has been fixed in the stability fixes branch.
