### ISSUE TITLE
ViStart can't be launched. No skins available?

### ISSUE THREAD

**Issue by GeorgeK1ng** [lee-soft/ViStart#3]
Hi,

I just discovered, this project is now opensource. I have downloaded latest compiled version here. Also with GDIPlusWrapper.dll.

I have placed GDIPlusWrapper.dll in same directory as ViStart - %ProgramFiles%\ViStart, then regsvr32 GDIPlusWrapper.dll.

But I can't launch ViStart v8.1.0.5254 - it hangs on "No skins available". What's wrong with that please?

![ViStart bug](https://user-images.githubusercontent.com/98261225/213790994-34e753f4-9dc1-460f-8a96-b7d39d636827.png)

**Comment by lee-soft** [comment]
Copy the contents of the "Skins" folder into %appdata%\ViStart\_skins"

The directory structure should look like this
"%appdata%\ViStart\_skins\Windows 7 Start Menu\layout.xml"

**Comment by GeorgeK1ng** [comment]
Thanks, now it works. 

I just noticed this version have ugly scroolbar when I'm browing all programs. Any idea about it?
![ViStart Ugly Scrollbar](https://user-images.githubusercontent.com/98261225/214031681-9c1f1bc6-1153-4a1f-99d2-b4a22476686b.png)

**Comment by lee-soft** [comment]
In the repository on github there is a vistart.manifest file you need to place in the same folder as the main executable. [ViStart.manifest](https://github.com/lee-soft/ViStart/blob/main/ViStart.manifest)

**Comment by GeorgeK1ng** [comment]
I'm still facing same issue with scrollbar. I have added manifest file and rebooted.
![vistart manifest](https://user-images.githubusercontent.com/98261225/214072408-fae76db7-5900-47f7-8525-7a45ac52f363.png)
![vistart manifest ugly](https://user-images.githubusercontent.com/98261225/214072413-eab790e8-60ef-4af9-8638-fc8e584eb7ab.png)

**Comment by lee-soft** [comment]
Try renaming the manifest to ViStart.exe.manifest and restart the executable

**Comment by GeorgeK1ng** [comment]
Silly me, I have really forgot to place extension to file name. Thanks, now it looks much better!
![ViStart Fixed Scrollbar](https://user-images.githubusercontent.com/98261225/214328037-895430b6-9ec4-467a-bf69-7aaa42bf3249.png)
