### ISSUE TITLE
Translations seems incomplete / not working on some places

### ISSUE THREAD

**Issue by GeorgeK1ng** [lee-soft/ViStart#4]
I have translated English.xml as Czech.xml. ViStart automatically load Czech language when used under Czech Windows XP SP3+.
But I noticed few things that seems to be broken.

Right click on frequently used applications
- everything is in English, almost all strings are in Language file
- "Remove from list" and "Send to desktop" string is missing in Language file and is non translatable?
- Send to ViPad, ViPad is not installed, so it shouldn't be here in my opinion + missing string in Language file
![ViStart_MissingTranslation_RighClick](https://user-images.githubusercontent.com/98261225/214168228-edde38d7-a3a4-42c3-9a64-e00305d2cbfd.png)

- Right click on applications when browsing All programs
![ViStart_MissingTranslation_RighClick2](https://user-images.githubusercontent.com/98261225/214171448-211ce283-4045-43e1-b2a6-877fe9a39079.png)

- Missing translations for "Programs" and "Files" when using Start search
![ViStart_MissingTranslation_Search](https://user-images.githubusercontent.com/98261225/214171451-7f10fbef-a75a-4933-b436-482dbbb9722d.png)

Czech.xml
`<strings>

    <string value="Odhlásit se" id="strLogOff" />
    <string value="Přepnout uživatele" id="strSwitchUser"  />
    <string value="Vypnout" id="strShutdown" />
    <string value="Restartovat" id="strRestart" />
    <string value="Režim spánku" id="strStandBy" />
    <string value="Hibernace" id="strHibernate" />
    <string value="Ukončit" id="strExit" />
    <string value="O programu" id="strAbout" />
    <string value="Nastavení" id="strOptions" />
    
    <string value="Všechny programy" id="strAllPrograms" />
    <string value="Zpět" id="strBack" />
    
    <string value="Kritériím vyhledávání neodpovídají žádné programy" id="strNotFound" />
    <string value="Zobrazit další výsledky" id="strSeeAllResults" />
    <string value="Prohledat programy" id="strStartSearch" />
    
    <string value="Nastavení" id="strProgramOptions" />

    <string value="Povolit funkci Auto-Click" id="strEnableAutoClick" />
    <string value="Zobrazit ikonu ViStart u hodin" id="strShowTrayIcon" />
    <string value="Spustit při startu počítače" id="strStartWithWindows" />
    <string value="Vymazat seznam často používaných programů" id="strClearFrequentList" />
    <string value="Možnosti indexování" id="strIndexOptions" />
    <string value="Otevřít ViStart pomocí klávesy Windows" id="strFilterWinKey" />
    
    <string value="Vybrat nový vzhled nabídky Start" id="strNewSkin" />
    <string value="Vybrat nový obrázek tlačítka Start" id="strOrbNew" />
    <string value="Resetovat tlačítko Start" id="strOrbReset" />
    <string value="Spustit" id="strRun" />
    <string value="Režim spánku" id="strSleep" />
    
    <string value="OK" id="strOK" />
    <string value="Storno" id="strCancel" />
    <string value="Procházet" id="strBrowse" />
    
    <string value="Otevřít" id="strOpen" />
    <string value="Don't show option in navigation pane" id="strHideOption" />
    <string value="Don't pop out folder contents" id="strDontPopOut" />
    <string value="Pop out folder contents" id="strPopOut" />
    <string value="Přejmenovat" id="strRename" />
    <string value="Vlastnosti" id="strProperties" />
    
    <string value="Sbalit" id="strCollapse" />
    <string value="Rozbalit" id="strExpand" />
    <string value="Spustit jako správce" id="strRunAsAdmin" />
    <string value="Odepnout z nabídky Start" id="strUnpinToStartMenu" />
    <string value="Připnout k nabídce Start" id="strPinToStartMenu" />

    <string value="Dokumenty" id="strDocuments" />
    <string value="Obrázky" id="strPictures" />
    <string value="Hudba" id="strMusic" />
    <string value="Videa" id="strVideos" />
    <string value="Hry" id="strGames" />
    <string value="Počítač" id="strComputer" />
    <string value="Poslední dokumenty" id="strRecent" />
    <string value="Síť" id="strNetwork" />
    <string value="Připojit k" id="strConnectTo"  />
    <string value="Ovládací panely" id="strControlPanel" />
    <string value="Nápověda a podpora" id="strHelp" />

</strings>
`

**Comment by GeorgeK1ng** [comment]
@lee-soft I would like to try to compile it myself. But I have issue with finding all needed files. I’m usable to find GDIPlus.TLB. And download link for HookMe.zip doesn’t work on my side.

Thats so sad, that I’m stuck on this step. Can you please send me these files? Otherwise I cant set up build environment.

**Comment by lee-soft** [comment]
Maybe you can create a branch and we can merge those changes in.

**Comment by GeorgeK1ng** [comment]
@lee-soft I have created fork and added some changes. Hope you like these changes.

https://github.com/lee-soft/ViStart/pull/5#issue-1560238961

ViStart v8.1.5255
- Improved translations, every visible element under Windows XP host can be now translated using Language.xml
- Added new translatable elements into all available languages
- Added Czech.xml
- Added new context menu in NavigationPane on custom items - Open, Rename and Hide
- Added new context menu to "Computer" - Manage, Search
- Added new context menu to "Computer" - Show on desktop / Hide from desktop
- Added new context menu "Explore" when browsing All programs to be able open whole folder
- Removed ViPad context menu when ViPad is not running or not installed. No more "online" feature in context menu
- Removed More themes and More Orbs online buttons. No more "online" features from Settings
- Realigned buttons on Style configuration page
- Realigned elemens on About page and added current build visibility
- Updated settings.xml with new defaults
- Fixed "No skins available", if doesn't exist %APPDATA%\ViStart use current EXE dir if _skins folder exist there

Known bugs:
1) When using Start search "Files" string can't be translated right now, I can't find correct place to replace this string with Language related string saved as "StrFiles" in Language.xml
2) NavigationPane font color is always white, this needs to be solved and enable some kind of Font Color option into layout.xml
3) When using Right click on "Run..." StartMenu keeps open and Run dialogbox is not on correct place

I hope you can help me with these known bugs. "Files" is only last remaining word in whole ViStart UI under XP that needs to be loaded from translations to make great user experience on any language.

Also set Font Color on Navigation pane using layout.xml is important for creating better skins.

**Comment by GeorgeK1ng** [comment]
@lee-soft Any idea about "strFiles" translation? This one is crucial to make UI perfect on any language

Also, where I can update ViStart icon? In previous version there was much better icon than now.

**Comment by GeorgeK1ng** [comment]
Most of these issues are fixed in ViStart v8.1.5255. Opening special ticket for last remaining issue to make it clear.
